FROM python:3.11.4

WORKDIR /app
ENV SECRET_KEY=$SECRET_KEY
ENV DB_URL=$DB_URL

COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python manage.py collectstatic --noinput
