# Generated by Django 4.2.3 on 2023-07-10 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='geocode_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата запроса'),
        ),
    ]
