# Generated by Django 4.2.3 on 2023-07-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('accepted', 'Принят'), ('restaurant', 'Передан в ресторан'), ('courier', 'Передан курьеру'), ('completed', 'Завершен')], db_index=True, default='unprocessed', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='firstname',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Имя'),
        ),
    ]
