# Generated by Django 4.2.3 on 2023-07-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_status_alter_order_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('accepted', 'Принят'), ('restaurant', 'Передан в ресторан'), ('courier', 'Передан курьеру'), ('completed', 'Завершен')], db_index=True, default='unprocessed', max_length=20, verbose_name='Статус'),
        ),
    ]
