# Generated by Django 4.2.3 on 2023-07-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_call_time_order_completed_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentstatus',
            field=models.CharField(choices=[('cash', 'Наличный расчет'), ('cashless', 'Безналичный расчет'), ('transfer', 'Расчет переводом')], db_index=True, default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
