# Generated by Django 4.2.3 on 2023-07-09 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='foodcartapp.restaurant', verbose_name='Ресторан'),
        ),
    ]
