# Generated by Django 4.2.3 on 2023-07-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Restaurant',
            new_name='restaurant',
        ),
    ]
