# Generated by Django 4.2.3 on 2023-07-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_order_paymentstatus_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentstatus',
            field=models.CharField(choices=[(0, 'Наличный расчет'), (1, 'Безналичный расчет'), (2, 'Расчет переводом')], db_index=True, default=0, max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
