# Generated by Django 4.2.3 on 2023-07-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_order_paymentstatus_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentstatus',
            field=models.IntegerField(choices=[(0, 'Наличный расчет'), (1, 'Безналичный расчет'), (2, 'Расчет переводом'), (3, 'Не указан')], db_index=True, default=3, verbose_name='Способ оплаты'),
        ),
    ]
