# Generated by Django 4.2.3 on 2023-07-17 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_rename_paymentstatus_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='foodcartapp.restaurant', verbose_name='Готовит ресторан'),
        ),
    ]
