FROM nginx:latest

WORKDIR /app

RUN apt-get update \
    && apt-get install -y certbot python-certbot-nginx\
    && rm -rf /var/lib/apt/lists/*

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY certbot-renew.sh /etc/periodic/daily/certbot-renew

RUN chmod +x /etc/periodic/daily/certbot-renew

CMD ["nginx", "-g", "daemon off;"]