version: '3.8'
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?}
      POSTGRES_DB: ${POSTGRES_DB?}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

#  frontend:
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile.node
#    depends_on:
#      - postgres
#    volumes:
#      - bundles:/app/bundles

  django:
    build:
      context: ../backend
      dockerfile: Dockerfile.django
      args:
        SECRET_KEY: ${SECRET_KEY?}
        DB_URL: ${DB_URL?}
    depends_on:
      - postgres
#      - frontend
    environment:
      SECRET_KEY: ${SECRET_KEY?}
      DEBUG: ${DEBUG?}
      DB_URL: ${DB_URL?}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS?}
      YANDEX_GEOCODER_API_KEY: ${YANDEX_GEOCODER_API_KEY?}
      ROLLBAR_ACCESS_TOKEN: ${ROLLBAR_ACCESS_TOKEN?}
      ROLLBAR_ENVIRONMENT: ${ROLLBAR_ENVIRONMENT?}
    command: sh -c "python manage.py migrate --noinput && gunicorn -w 3 star_burger.wsgi:application --bind 0.0.0.0:8081"
    ports:
      - "8081:8081"
    volumes:
#     том ниже временно отключен (включить после копирования статики на хост)
      - /www/starburger/staticfiles:/app/staticfiles
      - /www/starburger/media:/app/media
#      - bundles:/app/bundles

volumes:
  pg_data:
#  bundles:
