version: '3.8'
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?}
      POSTGRES_DB: ${POSTGRES_DB?}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.node.production
    depends_on:
      - postgres
    volumes:
      - bundles:/app/bundles

  django:
    build:
      context: ../backend
      dockerfile: Dockerfile.django.production
    depends_on:
      - postgres
      - frontend
    environment:
      SECRET_KEY: ${SECRET_KEY?}
      DEBUG: ${DEBUG?}
      DB_URL: ${DB_URL?}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS?}
      YANDEX_GEOCODER_API_KEY: ${YANDEX_GEOCODER_API_KEY?}
      ROLLBAR_ACCESS_TOKEN: ${ROLLBAR_ACCESS_TOKEN?}
      ROLLBAR_ENVIRONMENT: ${ROLLBAR_ENVIRONMENT?}
    command: /app/prepare-and-start.sh
    ports:
      - "8081:8081"
    volumes:
      - /www/starburger/static:/app/staticfiles
      - /www/starburger/media:/app/media


volumes:
  static:
  media:
  pg_data:
  bundles:
